import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Banner } from '@/components/banner'
import { NavBar } from '@/components/NavBar'
import { Session } from 'next-auth'
import { AuthProvider } from './auth/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { session, ...params },
}: {
  children: React.ReactNode,
  params: { session: Session },
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          <Banner isCollapsed={true} />
          <NavBar />

          <div>
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
